name: Build and Push Multi-Arch Chrony Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/freemankevin/chrony-amd64:latest
            ghcr.io/freemankevin/chrony-amd64:${{ github.sha }}

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/freemankevin/chrony-arm64:latest
            ghcr.io/freemankevin/chrony-arm64:${{ github.sha }}

      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/freemankevin/chrony:latest \
            ghcr.io/freemankevin/chrony-amd64:latest \
            ghcr.io/freemankevin/chrony-arm64:latest

      - name: Verify Tags
        run: |
          echo "Checking tags in GHCR..."
          docker manifest inspect ghcr.io/freemankevin/chrony-amd64:latest || echo "Tag chrony-amd64:latest not found"
          docker manifest inspect ghcr.io/freemankevin/chrony-arm64:latest || echo "Tag chrony-arm64:latest not found"
          docker manifest inspect ghcr.io/freemankevin/chrony:latest || echo "Tag chrony:latest not found"